language: python

python:
  - 2.7
  # - 3.3
  # - 3.4
env:
  # - VIM_VERSION="74"
  - VIM_VERSION="NEOVIM"

# Disable python3 testing with Neovim: https://github.com/neovim/neovim/issues/1829
matrix:
  exclude:
    - python: 3.3
      env: VIM_VERSION="NEOVIM"
    - python: 3.4
      env: VIM_VERSION="NEOVIM"

install: 
   - sudo ./travis_install.sh "${VIM_VERSION}" "$(which python)"
   - pip install neovim

before_script:
  - tmux new -d -s vim

script: 
   - ./travis_script.sh

